# Generated by Django 5.2 on 2026-05-27 03:18

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, help_text='Filled in when the book is returned.', null=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='catalog.bookcopy')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='users.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='users.memberprofile')),
            ],
            options={
                'verbose_name': 'Borrow Transaction',
                'verbose_name_plural': 'Borrow Transactions',
                'db_table': 'borrow_transactions',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fine amount in IDR.', max_digits=12)),
                ('paid_date', models.DateField(blank=True, help_text='Date the fine was settled.', null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('borrow_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='transactions.borrowtransaction')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'db_table': 'fines',
            },
        ),
    ]
