# Generated by Django 5.2 on 2026-05-28 08:16

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fine_type', models.CharField(choices=[('overdue', 'Overdue'), ('damage', 'Damage'), ('loss', 'Loss'), ('other', 'Other')], db_index=True, default='overdue', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional notes from staff explaining the reason for this fine.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fine amount in IDR.', max_digits=12)),
                ('paid_date', models.DateField(blank=True, help_text='Date the fine was settled.', null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10)),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'db_table': 'fines',
            },
        ),
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, help_text='Filled in when the book is returned.', null=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='catalog.bookcopy')),
            ],
            options={
                'verbose_name': 'Borrow Transaction',
                'verbose_name_plural': 'Borrow Transactions',
                'db_table': 'borrow_transactions',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
