# Generated by Django 5.2 on 2026-05-28 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='users.library'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='users.memberprofile'),
        ),
        migrations.AddField(
            model_name='fine',
            name='borrow_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='transactions.borrowtransaction'),
        ),
    ]
