# Generated by Django 5.2 on 2026-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='description',
            field=models.TextField(blank=True, help_text='Optional notes from staff explaining the reason for this fine.', null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='fine_type',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('damage', 'Damage'), ('loss', 'Loss'), ('other', 'Other')], db_index=True, default='overdue', max_length=10),
        ),
    ]
