# Generated by Django 5.2 on 2026-06-12 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('returned', 'Returned'), ('failed', 'Failed')], db_index=True, default='active', help_text='Lifecycle status of this borrow transaction.', max_length=10),
        ),
        migrations.AlterField(
            model_name='fine',
            name='borrow_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='transactions.borrowtransaction'),
        ),
    ]
