# Generated by Django 5.2 on 2026-06-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_borrowtransaction_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.UniqueConstraint(condition=models.Q(('fine_type', 'overdue')), fields=('borrow_transaction', 'fine_type'), name='unique_overdue_fine_per_transaction'),
        ),
    ]
