# Generated by Django 5.2 on 2026-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='UID from Supabase Auth. Used as the JWT bridge for authentication.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sso_id',
            field=models.CharField(blank=True, db_index=True, help_text='UID from the campus SSO provider (future integration).', max_length=255, null=True, unique=True),
        ),
    ]
