# Generated by Django 5.2 on 2026-06-28 14:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_supabase_uid_alter_user_sso_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='user_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
