# Generated by Django 5.2 on 2026-06-28 14:24

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_cover_image_alter_bookcopy_book'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='book_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['author'], name='book_author_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
