# Generated by Django 5.2 on 2026-06-28 14:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_author_alter_book_title_and_more'),
        ('users', '0003_user_user_name_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category'], name='book_category_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['isbn'], name='bookcopy_isbn_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['publisher'], name='bookcopy_publisher_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
